### PR TITLE
Updated to 1.3

### PR DESCRIPTION
**Pull request by emipa606**

### CODE REVIEW

**Comment by maarxx** [comment]
Hello! Thank you for all the Pull Requests! I appreciate it!

Your timing is good, I've been looking to get back into Rimworld some, but I have kids now and very little time. I've been trying to get around to them, but I'm not sure how soon it'll happen.

I don't mind if you move all the files into a different directory named `Source/`, but the way it was done here, it makes the Pull Requests impossible to read. It looks like every file was deleted and recreated, and every line rewritten, hundreds of lines of change, so I can't tell what was actually modified.

The Pull Requests need to be rebased onto a commit that does something like `git mv ./SmarterScheduling ./Source` so that it detects the file renames and highlights only files that were **actually** changed.

I think I could do this myself as well, and I intend to at some point, but I haven't found the time yet. If you find the time first, feel free, it would expedite the process, otherwise, I'll get to it when I can.

Thank you again!

Linking all the other PRs so they have references to this conversation:

https://github.com/maarxx/MeditateAsWorkType/pull/6
https://github.com/maarxx/SmarterDoctors/pull/5
https://github.com/maarxx/ModButtons/pull/5
https://github.com/maarxx/InjuryNotifier/pull/14
https://github.com/maarxx/BeatingsContinue/pull/4
https://github.com/maarxx/AccuraSight/pull/15
https://github.com/maarxx/LimitlessSelection/pull/6
https://github.com/maarxx/BulkAssigner/pull/19
https://github.com/maarxx/BetterNutrientPasteDispenserControls/pull/4
https://github.com/maarxx/HoldYourFire/pull/4
https://github.com/maarxx/FixStackedAnimalLag/pull/6
https://github.com/maarxx/ToxicFalloutManager/pull/6
https://github.com/maarxx/SnoozeAlerts/pull/5
https://github.com/maarxx/FirefightingControls/pull/6
https://github.com/maarxx/MoreAlerts/pull/51

**Comment by maarxx** [comment]
Hello! Thank you for all the Pull Requests! I appreciate it!

Your timing is good, I've been looking to get back into Rimworld some, but I have kids now and very little time. I've been trying to get around to them, but I'm not sure how soon it'll happen.

I don't mind if you move all the files into a different directory named `Source/`, but the way it was done here, it makes the Pull Requests impossible to read. It looks like every file was deleted and recreated, and every line rewritten, hundreds of lines of change, so I can't tell what was actually modified.

The Pull Requests need to be rebased onto a commit that does something like `git mv ./SmarterScheduling ./Source` so that it detects the file renames and highlights only files that were **actually** changed.

I think I could do this myself as well, and I intend to at some point, but I haven't found the time yet. If you find the time first, feel free, it would expedite the process, otherwise, I'll get to it when I can.

Thank you again!

Linking all the other PRs so they have references to this conversation:

https://github.com/maarxx/MeditateAsWorkType/pull/6
https://github.com/maarxx/SmarterDoctors/pull/5
https://github.com/maarxx/ModButtons/pull/5
https://github.com/maarxx/InjuryNotifier/pull/14
https://github.com/maarxx/BeatingsContinue/pull/4
https://github.com/maarxx/AccuraSight/pull/15
https://github.com/maarxx/LimitlessSelection/pull/6
https://github.com/maarxx/BulkAssigner/pull/19
https://github.com/maarxx/BetterNutrientPasteDispenserControls/pull/4
https://github.com/maarxx/HoldYourFire/pull/4
https://github.com/maarxx/FixStackedAnimalLag/pull/6
https://github.com/maarxx/ToxicFalloutManager/pull/6
https://github.com/maarxx/SnoozeAlerts/pull/5
https://github.com/maarxx/FirefightingControls/pull/6
https://github.com/maarxx/MoreAlerts/pull/51

**Comment by emipa606** [comment]
I guess its mostly since the code is reformatted using coding format standards that git thinks all files have been changed. Things like using var instead of the specific type-names and moving all classes into separate files. 
 
I can redo the work keeping your original formatting, Ill look into it this week.

**Comment by maarxx** [comment]
Master branch / Steam version updated for 1.4 now.

I probably won't backport to 1.3. I can accept a small PR for that if there's any desire.

Thanks for everything you do, Mlie.

**Pull request closed without merging**
